// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  return {
    routes: {"usecallback":{"path":"usecallback","id":"usecallback","parentId":"@@/global-layout","file":"usecallback.tsx"},"usememo":{"path":"usememo","id":"usememo","parentId":"@@/global-layout","file":"usememo.tsx"},"useref":{"path":"useref","id":"useref","parentId":"@@/global-layout","file":"useref.tsx"},"hooks":{"path":"hooks","id":"hooks","parentId":"@@/global-layout","file":"hooks.tsx"},"index":{"path":"/","id":"index","parentId":"@@/global-layout","file":"index.tsx"},"docs":{"path":"docs","id":"docs","parentId":"@@/global-layout","file":"docs.tsx"},"memo":{"path":"memo","id":"memo","parentId":"@@/global-layout","file":"memo.tsx"},"@@/global-layout":{"id":"@@/global-layout","path":"/","file":"@/layouts/index.tsx","isLayout":true}},
    routeComponents: {
'usecallback': React.lazy(() => import(/* webpackChunkName: "src__pages__usecallback" */'../../../src/pages/usecallback.tsx')),
'usememo': React.lazy(() => import(/* webpackChunkName: "src__pages__usememo" */'../../../src/pages/usememo.tsx')),
'useref': React.lazy(() => import(/* webpackChunkName: "src__pages__useref" */'../../../src/pages/useref.tsx')),
'hooks': React.lazy(() => import(/* webpackChunkName: "src__pages__hooks" */'../../../src/pages/hooks.tsx')),
'index': React.lazy(() => import(/* webpackChunkName: "src__pages__index" */'../../../src/pages/index.tsx')),
'docs': React.lazy(() => import(/* webpackChunkName: "src__pages__docs" */'../../../src/pages/docs.tsx')),
'memo': React.lazy(() => import(/* webpackChunkName: "src__pages__memo" */'../../../src/pages/memo.tsx')),
'@@/global-layout': React.lazy(() => import(/* webpackChunkName: "layouts__index" */'@/layouts/index.tsx')),
},
  };
}
